# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.11

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:10.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: cashout
      - image: circleci/redis:4.0.11
        environment:
          REDIS_ADDR: localhost:6379

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/pinkgorilla/go-sample/starter-api
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1

      - run:
          command: build/migrate.sh
          environment:
              DB_CONNECTION_STRING: "postgres://postgres@localhost:5432/cashout?sslmode=disable"

      - run:
          command: build/test.sh
          environment:
              DB_CONNECTION_STRING: "postgres://postgres@localhost:5432/cashout?sslmode=disable"

      - run:
          name: Put code coverage to coveralls.io
          command: |
            go get github.com/mattn/goveralls
            goveralls -coverprofile=/tmp/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN 